services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"   # host:container
    command: ["--default-authentication-plugin=caching_sha2_password","--port=3307"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "blog", "-pblog", "-P", "3307"]
      interval: 5s
      timeout: 3s
      retries: 10
